# Generated by Django 4.0.6 on 2022-11-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.CharField(blank=True, max_length=32, null=True)),
                ('program', models.CharField(blank=True, max_length=20, null=True)),
                ('pid', models.CharField(blank=True, max_length=8, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
